# Generated by Django 4.1.3 on 2022-11-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('contraseña', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Repetir_contraseña', models.IntegerField()),
            ],
        ),
    ]
